### ISSUE TITLE
文件较大时，经常就读取超时

### ISSUE THREAD

**Issue by xilost** [Zhaoss/VideoPlayerDemo#4]
显示是的okhttp超时，应该是缓存跟不上播放进度。

`12-08 21:07:24.543 20594-20594/com.weibo.wbalk V/AudioManager: playSoundEffect   effectType: 0
12-08 21:07:42.167 20594-23391/com.weibo.wbalk W/System.err: java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:232)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
        at okio.RealBufferedSource.read(RealBufferedSource.java:47)
12-08 21:07:42.168 20594-23391/com.weibo.wbalk W/System.err:     at okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:363)
        at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:407)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:440)
        at java.io.InputStream.read(InputStream.java:101)
        at com.weibo.wbalk.app.utils.CacheMediaDataSource.readByteBySize(CacheMediaDataSource.java:132)
        at com.weibo.wbalk.app.utils.CacheMediaDataSource.readAt(CacheMediaDataSource.java:80)
12-08 21:07:42.169 20594-23391/com.weibo.wbalk W/System.err: Caused by: java.net.SocketException: Socket closed
        at java.net.SocketInputStream.read(SocketInputStream.java:203)
        at java.net.SocketInputStream.read(SocketInputStream.java:139)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)`

**Comment by Zhaoss** [comment]
我用的是okhttp默认的请求超时时间 应该是10秒 你调大一点就好了

**Comment by xilost** [comment]
@Zhaoss 网络不好的时候还是有点问题。
还有个问题，怎么设置播放的时候按照视频大小显示呢？现在是自动拉伸。
